heros = [
    {
        "nom": "Goku",
        "description": "Guerrier Saiyan légendaire, défenseur de la Terre aux pouvoirs infinis.",
        "pv": 500,
        "pv_max": 500,
        "defense": 20,
        "initiative": 22,
        "actions": ["Kamehameha"],
        "typeDegats": "foudre",
        "etat": "normal",
        "degats": (3, 10),
        "arme": None,
        "inventaire": [],
        "peut_fusionner": True,
        "fusion_avec": "Vegeta",
        "Carte": None
    },
    {
        "nom": "Gohan",
        "description": "Fils de Goku, demi-Saiyan au potentiel caché qui surpasse son père.",
        "pv": 4,
        "pv_max": 420,
        "defense": 5,
        "initiative": 19,
        "actions": ["Kamehameha"],
        "typeDegats": "foudre",
        "etat": "normal",
        "degats": (2, 10),
        "arme": None,
        "inventaire": [],
        "peut_fusionner": False,
        "fusion_avec": None,
        "Carte": None
    },
    {
        "nom": "Vegeta",
        "description": "Prince des Saiyans, rival éternel de Goku, fier guerrier d'élite.",
        "pv": 480,
        "pv_max": 480,
        "defense": 19,
        "initiative": 20,
        "actions": ["Final Flash"],
        "typeDegats": "foudre",
        "etat": "normal",
        "degats": (3, 10),
        "arme": None,
        "inventaire": [],
        "peut_fusionner": True,
        "fusion_avec": "Goku",
        "Carte": None
    },
    {
        "nom": "Trunks",
        "description": "Guerrier du futur, fils de Vegeta, porteur de l'épée légendaire.",
        "pv": 350,
        "pv_max": 350,
        "defense": 17,
        "initiative": 18,
        "actions": ["Burning Attack"],
        "typeDegats": "tranchant",
        "etat": "normal",
        "degats": (3, 10),
        "arme": None,
        "inventaire": [],
        "peut_fusionner": True,
        "fusion_avec": "Goten",
        "Carte": None
    },
    {
        "nom": "Goten",
        "description": "Fils cadet de Goku, prodige Saiyan et meilleur ami de Trunks.",
        "pv": 320,
        "pv_max": 320,
        "defense": 15,
        "initiative": 17,
        "actions": ["Kamehameha"],
        "typeDegats": "foudre",
        "etat": "normal",
        "degats": (2, 10),
        "arme": None,
        "inventaire": [],
        "peut_fusionner": True,
        "fusion_avec": "Trunks",
        "Carte": None
    },
    {
        "nom": "Krilin",
        "description": "Meilleur ami humain de Goku, maître du Destructo Disk et du Kamehameha.",
        "pv": 180,
        "pv_max": 180,
        "defense": 13,
        "initiative": 16,
        "actions": ["Destructo Disk"],
        "typeDegats": "tranchant",
        "etat": "normal",
        "degats": (2, 6),
        "arme": None,
        "inventaire": [],
        "peut_fusionner": False,
        "fusion_avec": None,
        "Carte": None
    }
]

hero_fusion = [
    {
        "nom": "Gotenks",
        "description": "Fusion légendaire de Trunks et Goten, puissance démultipliée.",
        "pv": 620,
        "pv_max": 620,
        "defense": 22,
        "initiative": 21,
        "actions": ["Kamehameha Jr"],
        "typeDegats": "foudre",
        "etat": "normal",
        "degats": (4, 12),
        "arme": None,
        "inventaire": [],
        "peut_fusionner": False,
        "fusion_avec": None,
        "Carte": None
    },
    {
        "nom": "Gogeta",
        "description": "Fusion parfaite de Goku et Vegeta, la plus puissante jamais vue.",
        "pv": 1280,
        "pv_max": 1280,
        "defense": 28,
        "initiative": 27,
        "actions": ["Big Bang Kamehameha"],
        "typeDegats": "foudre",
        "etat": "normal",
        "degats": (5, 12),
        "arme": None,
        "inventaire": [],
        "peut_fusionner": False,
        "fusion_avec": None,
        "Carte": None
    }
]

mechants = [
    {
        "nom": "Broly",
        "description": "Saiyan légendaire à la puissance incontrôlable, destructor de planètes.",
        "pv": 600,
        "pv_max": 600,
        "defense": 18,
        "initiative": 14,
        "actions": ["Eraser Cannon"],
        "typeDegats": "foudre",
        "etat": "normal",
        "degats": (4, 12),
        "Carte": None,
        "resistances": ["contondant", "tranchant", "percant"]
    },
    {
        "nom": "Freezer",
        "description": "Empereur galactique tyrannique, destructeur de la planète Vegeta.",
        "pv": 520,
        "pv_max": 520,
        "defense": 10,
        "initiative": 18,
        "actions": ["Death Beam"],
        "typeDegats": "glace",
        "etat": "normal",
        "degats": (3, 12),
        "Carte": None,
        "resistances": ["tranchant", "percant", "glace"]
    },
    {
        "nom": "Cell",
        "description": "Androïde parfait créé par le Dr Gero, absorbeur de puissance.",
        "pv": 450,
        "pv_max": 450,
        "defense": 19,
        "initiative": 17,
        "actions": ["Kamehameha Solaire"],
        "typeDegats": "poison",
        "etat": "normal",
        "degats": (3, 10),
        "Carte": None,
        "resistances": ["poison", "feu"]
    },
    {
        "nom": "Buu Majin",
        "description": "Créature magique antique à la régénération infinie.",
        "pv": 700,
        "pv_max": 700,
        "defense": 15,
        "initiative": 12,
        "actions": ["Candy Beam"],
        "typeDegats": "magie",
        "etat": "normal",
        "degats": (4, 10),
        "Carte": None,
        "resistances": ["contondant", "tranchant", "percant", "feu"]
    },
    {
        "nom": "Raditz",
        "description": "Frère aîné de Goku, premier ennemi Saiyan à menacer la Terre.",
        "pv": 220,
        "pv_max": 220,
        "defense": 14,
        "initiative": 15,
        "actions": ["Saturday Crush"],
        "typeDegats": "foudre",
        "etat": "normal",
        "degats": (2, 8),
        "Carte": None,
        "resistances": ["contondant"]
    },
    {
        "nom": "Janemba",
        "description": "Démon né de l'énergie maléfique des enfers, capable de déformer la réalité.",
        "pv": 620,
        "pv_max": 620,
        "defense": 19,
        "initiative": 16,
        "actions": ["Dimension Sword"],
        "typeDegats": "magique",
        "etat": "normal",
        "degats": (4, 12),
        "Carte": None,
        "resistances": ["contondant", "tranchant", "magique"]
    },
    {
        "nom": "Cooler",
        "description": "Frère aîné de Freezer, plus froid et plus impitoyable.",
        "pv": 540,
        "pv_max": 540,
        "defense": 21,
        "initiative": 19,
        "actions": ["Supernova de Cooler"],
        "typeDegats": "feu",
        "etat": "normal",
        "degats": (4, 12),
        "Carte": None,
        "resistances": ["tranchant", "percant", "glace"]
    },
    {
        "nom": "Zamasu",
        "description": "Dieu Kaïo devenu immortel, convaincu que les mortels doivent être anéantis.",
        "pv": 700,
        "pv_max": 700,
        "defense": 23,
        "initiative": 18,
        "actions": ["Tranche Sainte"],
        "typeDegats": "magique",
        "etat": "normal",
        "degats": (4, 12),
        "Carte": None,
        "resistances": ["contondant", "tranchant", "percant", "feu"]
    },
]

etats = [
    "normal",
    "empoisonné",
    "saigne",
    "étourdi",
    "brûlé",
    "paralysé",
    "Boosté",
    "Affaibli",
    "mort"
]

types_degats = [
    "contondant",
    "tranchant",
    "perçant",
    "feu",
    "poison",
]

armes = [
    "Épée de Trunks",
    "Bâton Magique de Goku",
    "Destructo Disk",
    "Queue Saiyan",
    "Gants empoisonnés",
    "Souffle de Freezer"
]